apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../infrastructure/k8s/backend-deployment.yaml
  - ../../../../infrastructure/k8s/frontend-deployment.yaml
  - ../../../../infrastructure/k8s/ingress.yaml
  - ../../../../infrastructure/k8s/postgres-statefulset.yaml
