apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: staging
namePrefix: staging-

commonLabels:
  environment: staging
  tier: application

patches:
  # Downscale staging resources to 1 replica to optimize resource utilization
  - target:
      kind: Deployment
      name: alignops-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: alignops-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
