apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alignops.fullname" . }}-secrets
  labels:
    {{- include "alignops.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgres.dbPassword | b64enc | quote }}
  database-url: {{ .Values.backend.env.databaseUrl | b64enc | quote }}
  jwt-secret: {{ .Values.backend.env.jwtSecret | b64enc | quote }}
